### ISSUE TITLE
how to use the hyper themes?

### ISSUE THREAD

**Issue by rcrooks** [protesilaos/prot16#5]
Hi @protesilaos - trying to figure out how to use the noir hyper theme - any clues? (sorry, new to hyper)

**Comment by protesilaos** [comment]
Hi @rcrooks! Just realised that I have not included the relevant `README`—apologies, will do so as soon as possible.

To the point: you will need to edit the default config file. This should be located at `~/.hyper.js`.  Then you can copy the contents of either [noir-dark.js](https://github.com/protesilaos/prot16/blob/master/noir/hyper/noir-dark.js) or [noir-light.js](https://github.com/protesilaos/prot16/blob/master/noir/hyper/noir-light.js). These files I have here are derived from the generic config file, with the only changes being those of the colour values.

Please let me know if you need any help.

PS. Hyper themes tend to be distributed as npm packages, which is a slightly better approach and simpler for the user. I don't do that due to the extra trouble of maintaining all those ports.

**Comment by rcrooks** [comment]
ah, I see -- thanks! I understand about maintaining the packages.

**Comment by protesilaos** [comment]
Just to note that I updated each item's README with instructions such as these.

Relevant commits: 

(1) https://github.com/protesilaos/prot16/commit/0f89f8f3164fc7be49f75c9d74ce279d8b5c64dd
(2) https://github.com/protesilaos/prot16/commit/c25c0439adc7f80857f27e3b83c310fcb2af94ff

Closing this issue.

**Comment by rcrooks** [comment]
Nice - thanks!
